theme: jekyll-theme-minimal
title: Sanjiv's Profile
description: An applied AI researcher with a background in computer vision, ubiquitous computing, and human-centered system design. I specialize in developing context-aware, transparent, and scalable AI solutions that bridge research and real-world applications. I am driven to translate academic research into industrial, explainable solutions that deliver business value and elevate user experience.
